<script setup>
import { computed } from 'vue';
import { Link, router } from '@inertiajs/vue3';
import SuperAdminLayout from '@/Layouts/SuperAdminLayout.vue';
import BillingWorkspaceNav from '@/Components/SuperAdmin/BillingWorkspaceNav.vue';
import BillingEntityTrail from '@/Components/SuperAdmin/BillingEntityTrail.vue';
import { ArrowLeft, CalendarClock, CircleDollarSign, CreditCard, FileText, RefreshCw, Webhook } from 'lucide-vue-next';

const props = defineProps({ invoice: Object });
const cards = computed(() => [
    { label: 'Totali', value: money(props.invoice.total_cents), icon: FileText },
    { label: 'Paguar', value: money(props.invoice.amount_paid_cents), icon: CreditCard },
    { label: 'Mbetur', value: money(props.invoice.balance_cents), icon: CircleDollarSign },
    { label: 'Afati', value: date(props.invoice.due_on), icon: CalendarClock },
]);

function money(cents) { return new Intl.NumberFormat('sq-AL', { style: 'currency', currency: props.invoice.currency, minimumFractionDigits: 2 }).format((cents || 0) / 100); }
function date(value) { return value ? new Intl.DateTimeFormat('sq-AL', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${value}T12:00:00`)) : '—'; }
function dateTime(value) { return value ? new Intl.DateTimeFormat('sq-AL', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'; }
function statusClass(status) { return { draft: 'bg-neutral-100 text-neutral-600', open: 'bg-amber-50 text-amber-700', paid: 'bg-emerald-50 text-emerald-700', overdue: 'bg-red-50 text-red-700', void: 'bg-neutral-100 text-neutral-500', succeeded: 'bg-emerald-50 text-emerald-700', failed: 'bg-red-50 text-red-700', pending: 'bg-amber-50 text-amber-700' }[status] || 'bg-neutral-100 text-neutral-600'; }
function statusLabel(status) { return { draft: 'Draft', open: 'Për pagesë', paid: 'Paguar', overdue: 'Me vonesë', void: 'Anuluar' }[status] || status; }
function publishInvoice() { router.patch(`/super-admin/billing/invoices/${props.invoice.id}/publish`); }
function voidInvoice() { if (window.confirm(`Të anulohet fatura ${props.invoice.number}?`)) router.patch(`/super-admin/billing/invoices/${props.invoice.id}/void`); }
</script>

<template>
    <SuperAdminLayout :title="`${invoice.number} — Billing`">
        <div class="mx-auto max-w-7xl space-y-5">
            <BillingWorkspaceNav />
            <Link href="/super-admin/billing/invoices" class="inline-flex items-center gap-2 text-xs font-semibold text-neutral-500 no-underline hover:text-emerald-700"><ArrowLeft class="h-4 w-4" /> Kthehu te faturat</Link>
            <header class="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
                <div class="space-y-3"><BillingEntityTrail :tenant="invoice.tenant" :subscription-id="invoice.subscription_id" :invoice="invoice" /><div class="flex flex-wrap items-center gap-3"><h1 class="text-3xl font-semibold tracking-tight text-neutral-950">{{ invoice.number }}</h1><span class="rounded-full px-2.5 py-1 text-xs font-semibold" :class="statusClass(invoice.status)">{{ statusLabel(invoice.status) }}</span></div><p class="text-sm text-neutral-500">{{ date(invoice.period_starts_on) }} – {{ date(invoice.period_ends_on) }} · {{ invoice.source === 'subscription_schedule' ? 'Krijuar nga abonimi' : 'Krijuar manualisht' }}</p></div>
                <div class="flex gap-2"><button v-if="invoice.status === 'draft'" class="rounded-xl border border-red-200 px-4 py-2 text-sm font-semibold text-red-700" @click="voidInvoice">Anulo</button><button v-if="invoice.status === 'draft'" class="rounded-xl bg-emerald-700 px-4 py-2 text-sm font-semibold text-white" @click="publishInvoice">Publiko</button><Link v-if="['open','overdue'].includes(invoice.status)" :href="`/super-admin/billing/payments?invoice_id=${invoice.id}`" class="rounded-xl bg-emerald-700 px-4 py-2 text-sm font-semibold text-white no-underline">Regjistro pagesë</Link></div>
            </header>
            <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article v-for="card in cards" :key="card.label" class="rounded-2xl border border-neutral-200 bg-white p-4 shadow-sm"><div class="flex items-center justify-between"><div><p class="text-xs font-medium text-neutral-500">{{ card.label }}</p><p class="mt-2 text-xl font-semibold text-neutral-950">{{ card.value }}</p></div><span class="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><component :is="card.icon" class="h-5 w-5" /></span></div></article></section>
            <div class="grid gap-5 xl:grid-cols-[minmax(0,1.6fr)_minmax(300px,.7fr)]">
                <div class="space-y-5">
                    <section class="overflow-hidden rounded-2xl border border-neutral-200 bg-white shadow-sm"><div class="border-b border-neutral-200 px-5 py-4"><h2 class="font-semibold">Zërat e faturës</h2></div><table class="min-w-full text-sm"><thead class="bg-neutral-50 text-left text-xs uppercase text-neutral-500"><tr><th class="px-5 py-3">Përshkrimi</th><th class="px-5 py-3 text-right">Njësi</th><th class="px-5 py-3 text-right">Shuma</th></tr></thead><tbody class="divide-y divide-neutral-100"><tr v-for="line in invoice.lines" :key="line.id"><td class="px-5 py-4"><strong class="block text-neutral-900">{{ line.description }}</strong><span class="text-xs text-neutral-400">{{ line.module_code }}</span></td><td class="px-5 py-4 text-right text-neutral-500">{{ money(line.unit_amount_cents) }}</td><td class="px-5 py-4 text-right font-semibold">{{ money(line.amount_cents) }}</td></tr></tbody><tfoot class="border-t border-neutral-200 text-sm"><tr v-if="invoice.discount_cents"><td colspan="2" class="px-5 py-3 text-neutral-500">Zbritje</td><td class="px-5 py-3 text-right text-emerald-700">−{{ money(invoice.discount_cents) }}</td></tr><tr><td colspan="2" class="px-5 py-4 font-semibold">Total</td><td class="px-5 py-4 text-right text-lg font-semibold">{{ money(invoice.total_cents) }}</td></tr></tfoot></table></section>
                    <section class="overflow-hidden rounded-2xl border border-neutral-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-neutral-200 px-5 py-4"><div><h2 class="font-semibold">Pagesat</h2><p class="mt-1 text-xs text-neutral-500">Pagesat e lidhura me këtë faturë.</p></div><CreditCard class="h-5 w-5 text-neutral-400" /></div><div v-if="invoice.payments.length" class="divide-y divide-neutral-100"><Link v-for="payment in invoice.payments" :key="payment.id" :href="`/super-admin/billing/payments/${payment.id}`" class="grid gap-2 px-5 py-4 text-sm no-underline hover:bg-neutral-50 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><strong class="text-emerald-700">{{ payment.number }}</strong><p class="mt-1 text-xs text-neutral-500">{{ payment.provider }} · {{ payment.method }} · {{ payment.recorder || 'Sistem' }}</p></div><span class="text-xs text-neutral-500">{{ dateTime(payment.paid_at) }}</span><strong class="text-neutral-900">{{ money(payment.amount_cents) }}</strong></Link></div><p v-else class="px-5 py-10 text-center text-sm text-neutral-400">Nuk ka pagesa të lidhura.</p></section>
                    <section class="overflow-hidden rounded-2xl border border-neutral-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-neutral-200 px-5 py-4"><div><h2 class="font-semibold">Tentativat e pagesës</h2><p class="mt-1 text-xs text-neutral-500">Çdo tentativë online dhe rezultati i saj.</p></div><RefreshCw class="h-5 w-5 text-neutral-400" /></div><div v-if="invoice.attempts.length" class="divide-y divide-neutral-100"><Link v-for="attempt in invoice.attempts" :key="attempt.id" :href="`/super-admin/billing/payment-attempts/${attempt.id}`" class="grid gap-2 px-5 py-4 text-sm no-underline hover:bg-neutral-50 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><strong class="text-emerald-700">Tentativa #{{ attempt.attempt_number }}</strong><p class="mt-1 text-xs text-neutral-500">{{ attempt.provider }} · {{ attempt.provider_attempt_id || 'pa external ID' }}</p></div><span class="rounded-full px-2.5 py-1 text-xs font-semibold" :class="statusClass(attempt.status)">{{ attempt.status }}</span><strong class="text-neutral-900">{{ money(attempt.amount_cents) }}</strong></Link></div><p v-else class="px-5 py-10 text-center text-sm text-neutral-400">Nuk ka tentativa online.</p></section>
                    <section class="overflow-hidden rounded-2xl border border-neutral-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-neutral-200 px-5 py-4"><div><h2 class="font-semibold">Provider events</h2><p class="mt-1 text-xs text-neutral-500">Webhook-et e lidhura drejtpërdrejt.</p></div><Webhook class="h-5 w-5 text-neutral-400" /></div><div v-if="invoice.events.length" class="divide-y divide-neutral-100"><Link v-for="event in invoice.events" :key="event.id" :href="`/super-admin/billing/provider-events/${event.id}`" class="flex items-center justify-between gap-3 px-5 py-4 text-sm no-underline hover:bg-neutral-50"><div><strong class="text-emerald-700">{{ event.event_type }}</strong><p class="mt-1 font-mono text-xs text-neutral-400">{{ event.external_id }}</p></div><span class="text-xs text-neutral-500">{{ dateTime(event.occurred_at) }}</span></Link></div><p v-else class="px-5 py-10 text-center text-sm text-neutral-400">Nuk ka provider events.</p></section>
                </div>
                <aside class="space-y-5"><section class="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm"><h2 class="font-semibold">Abonimi</h2><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between gap-3"><dt class="text-neutral-500">Statusi</dt><dd class="font-semibold">{{ invoice.subscription?.status || '—' }}</dd></div><div class="flex justify-between gap-3"><dt class="text-neutral-500">Cikli</dt><dd class="font-semibold">{{ invoice.subscription?.billing_cycle || '—' }}</dd></div><div class="flex justify-between gap-3"><dt class="text-neutral-500">Faturimi tjetër</dt><dd class="font-semibold">{{ dateTime(invoice.subscription?.next_billing_at) }}</dd></div></dl><Link :href="`/super-admin/tenants/${invoice.tenant.id}`" class="mt-5 block rounded-xl border border-neutral-200 px-3 py-2 text-center text-xs font-semibold text-neutral-700 no-underline hover:border-emerald-200 hover:text-emerald-800">Hap hotelin dhe abonimin</Link></section><section class="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm"><h2 class="font-semibold">Shënime</h2><p class="mt-3 whitespace-pre-wrap text-sm leading-6 text-neutral-500">{{ invoice.notes || 'Pa shënime.' }}</p></section></aside>
            </div>
        </div>
    </SuperAdminLayout>
</template>
