<script setup>
import { Link } from '@inertiajs/vue3';
import SuperAdminLayout from '@/Layouts/SuperAdminLayout.vue';
import BillingWorkspaceNav from '@/Components/SuperAdmin/BillingWorkspaceNav.vue';
import BillingEntityTrail from '@/Components/SuperAdmin/BillingEntityTrail.vue';
import { ArrowLeft, CreditCard, RefreshCw, Webhook } from 'lucide-vue-next';

const props = defineProps({ payment: Object });
function money(cents) { return new Intl.NumberFormat('sq-AL', { style: 'currency', currency: props.payment.currency, minimumFractionDigits: 2 }).format((cents || 0) / 100); }
function dateTime(value) { return value ? new Intl.DateTimeFormat('sq-AL', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'; }
function statusClass(status) { return { completed: 'bg-emerald-50 text-emerald-700', succeeded: 'bg-emerald-50 text-emerald-700', failed: 'bg-red-50 text-red-700', pending: 'bg-amber-50 text-amber-700', refunded: 'bg-blue-50 text-blue-700' }[status] || 'bg-neutral-100 text-neutral-600'; }
</script>

<template>
    <SuperAdminLayout :title="`${payment.number} — Pagesa`">
        <div class="mx-auto max-w-6xl space-y-5">
            <BillingWorkspaceNav />
            <Link href="/super-admin/billing/payments" class="inline-flex items-center gap-2 text-xs font-semibold text-neutral-500 no-underline hover:text-emerald-700"><ArrowLeft class="h-4 w-4" /> Kthehu te pagesat</Link>
            <header class="space-y-3"><BillingEntityTrail :tenant="payment.tenant" :subscription-id="payment.subscription?.id" :invoice="payment.invoice" :payment="payment" /><div class="flex flex-wrap items-center gap-3"><h1 class="text-3xl font-semibold tracking-tight text-neutral-950">{{ payment.number }}</h1><span class="rounded-full px-2.5 py-1 text-xs font-semibold" :class="statusClass(payment.status)">{{ payment.status }}</span></div><p class="text-sm text-neutral-500">{{ payment.provider }} · {{ payment.method }} · {{ dateTime(payment.paid_at) }}</p></header>
            <section class="grid gap-4 md:grid-cols-3"><article class="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm"><p class="text-xs font-medium text-neutral-500">Shuma</p><p class="mt-2 text-3xl font-semibold">{{ money(payment.amount_cents) }}</p></article><article class="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm"><p class="text-xs font-medium text-neutral-500">Referenca</p><p class="mt-2 break-all text-lg font-semibold">{{ payment.reference || payment.provider_payment_id || '—' }}</p></article><article class="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm"><p class="text-xs font-medium text-neutral-500">Regjistruar nga</p><p class="mt-2 text-lg font-semibold">{{ payment.recorder?.name || 'Sistemi' }}</p><p class="mt-1 text-xs text-neutral-400">{{ payment.recorder?.email }}</p></article></section>
            <div class="grid gap-5 lg:grid-cols-2">
                <section class="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><h2 class="font-semibold">Fatura e lidhur</h2><CreditCard class="h-5 w-5 text-neutral-400" /></div><template v-if="payment.invoice"><Link :href="`/super-admin/billing/invoices/${payment.invoice.id}`" class="mt-4 block rounded-xl border border-neutral-200 p-4 no-underline hover:border-emerald-200"><div class="flex items-center justify-between gap-3"><strong class="text-emerald-700">{{ payment.invoice.number }}</strong><span class="text-xs font-semibold text-neutral-500">{{ payment.invoice.status }}</span></div><div class="mt-4 grid grid-cols-2 gap-3 text-sm"><div><span class="block text-xs text-neutral-400">Totali</span><strong>{{ money(payment.invoice.total_cents) }}</strong></div><div><span class="block text-xs text-neutral-400">Mbetur</span><strong>{{ money(payment.invoice.balance_cents) }}</strong></div></div></Link></template><p v-else class="mt-4 text-sm text-neutral-400">Pagesa nuk ka faturë të lidhur.</p></section>
                <section class="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm"><h2 class="font-semibold">Hoteli dhe abonimi</h2><div class="mt-4"><BillingEntityTrail :tenant="payment.tenant" :subscription-id="payment.subscription?.id" /></div><dl class="mt-5 space-y-3 text-sm"><div class="flex justify-between"><dt class="text-neutral-500">Statusi i abonimit</dt><dd class="font-semibold">{{ payment.subscription?.status || '—' }}</dd></div><div class="flex justify-between"><dt class="text-neutral-500">Cikli</dt><dd class="font-semibold">{{ payment.subscription?.billing_cycle || '—' }}</dd></div></dl></section>
                <section class="overflow-hidden rounded-2xl border border-neutral-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-neutral-200 px-5 py-4"><div><h2 class="font-semibold">Tentativat</h2><p class="mt-1 text-xs text-neutral-500">Tentativat që çuan te kjo pagesë.</p></div><RefreshCw class="h-5 w-5 text-neutral-400" /></div><div v-if="payment.attempts.length" class="divide-y divide-neutral-100"><Link v-for="attempt in payment.attempts" :key="attempt.id" :href="`/super-admin/billing/payment-attempts/${attempt.id}`" class="flex items-center justify-between gap-3 px-5 py-4 text-sm no-underline hover:bg-neutral-50"><div><strong class="text-emerald-700">Tentativa #{{ attempt.attempt_number }}</strong><p class="mt-1 text-xs text-neutral-400">{{ attempt.provider }} · {{ dateTime(attempt.attempted_at) }}</p></div><span class="rounded-full px-2.5 py-1 text-xs font-semibold" :class="statusClass(attempt.status)">{{ attempt.status }}</span></Link></div><p v-else class="px-5 py-10 text-center text-sm text-neutral-400">Pagesë manuale ose pa tentativa provider-i.</p></section>
                <section class="overflow-hidden rounded-2xl border border-neutral-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-neutral-200 px-5 py-4"><div><h2 class="font-semibold">Provider events</h2><p class="mt-1 text-xs text-neutral-500">Eventet që konfirmuan ose ndryshuan pagesën.</p></div><Webhook class="h-5 w-5 text-neutral-400" /></div><div v-if="payment.events.length" class="divide-y divide-neutral-100"><Link v-for="event in payment.events" :key="event.id" :href="`/super-admin/billing/provider-events/${event.id}`" class="flex items-center justify-between gap-3 px-5 py-4 text-sm no-underline hover:bg-neutral-50"><div><strong class="text-emerald-700">{{ event.event_type }}</strong><p class="mt-1 text-xs text-neutral-400">{{ event.provider }}</p></div><span class="text-xs text-neutral-500">{{ dateTime(event.occurred_at) }}</span></Link></div><p v-else class="px-5 py-10 text-center text-sm text-neutral-400">Nuk ka provider events.</p></section>
            </div>
        </div>
    </SuperAdminLayout>
</template>
