<script setup>
import { Link } from '@inertiajs/vue3';
import SuperAdminLayout from '@/Layouts/SuperAdminLayout.vue';
import BillingWorkspaceNav from '@/Components/SuperAdmin/BillingWorkspaceNav.vue';
import BillingEntityTrail from '@/Components/SuperAdmin/BillingEntityTrail.vue';
import { ArrowLeft, Webhook } from 'lucide-vue-next';

const props = defineProps({ attempt: Object });
function money(cents) { return new Intl.NumberFormat('sq-AL', { style: 'currency', currency: props.attempt.currency, minimumFractionDigits: 2 }).format((cents || 0) / 100); }
function dateTime(value) { return value ? new Intl.DateTimeFormat('sq-AL', { dateStyle: 'medium', timeStyle: 'long' }).format(new Date(value)) : '—'; }
function statusClass(status) { return { succeeded: 'bg-emerald-50 text-emerald-700', failed: 'bg-red-50 text-red-700', pending: 'bg-amber-50 text-amber-700', processing: 'bg-blue-50 text-blue-700', requires_action: 'bg-purple-50 text-purple-700' }[status] || 'bg-neutral-100 text-neutral-600'; }
</script>

<template>
    <SuperAdminLayout :title="`Tentativa #${attempt.id} — Billing`">
        <div class="mx-auto max-w-6xl space-y-5"><BillingWorkspaceNav /><Link href="/super-admin/billing/payment-attempts" class="inline-flex items-center gap-2 text-xs font-semibold text-neutral-500 no-underline hover:text-emerald-700"><ArrowLeft class="h-4 w-4" /> Kthehu te tentativat</Link><header class="space-y-3"><BillingEntityTrail :tenant="attempt.tenant" :subscription-id="attempt.subscription_id" :invoice="attempt.invoice" :payment="attempt.payment" :attempt="attempt" /><div class="flex flex-wrap items-center gap-3"><h1 class="text-3xl font-semibold">Tentativa #{{ attempt.id }}</h1><span class="rounded-full px-2.5 py-1 text-xs font-semibold" :class="statusClass(attempt.status)">{{ attempt.status }}</span></div><p class="font-mono text-xs text-neutral-500">{{ attempt.provider }} / {{ attempt.provider_attempt_id || 'pa external ID' }}</p></header>
            <section class="grid gap-4 md:grid-cols-4"><article class="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm"><p class="text-xs text-neutral-500">Shuma</p><p class="mt-2 text-2xl font-semibold">{{ money(attempt.amount_cents) }}</p></article><article class="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm"><p class="text-xs text-neutral-500">Numri i tentativës</p><p class="mt-2 text-2xl font-semibold">{{ attempt.attempt_number }}</p></article><article class="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm"><p class="text-xs text-neutral-500">U tentua</p><p class="mt-2 text-sm font-semibold">{{ dateTime(attempt.attempted_at) }}</p></article><article class="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm"><p class="text-xs text-neutral-500">U zgjidh</p><p class="mt-2 text-sm font-semibold">{{ dateTime(attempt.resolved_at) }}</p></article></section>
            <div class="grid gap-5 lg:grid-cols-[1fr_1.4fr]"><section class="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm"><h2 class="font-semibold">Rezultati</h2><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between gap-3"><dt class="text-neutral-500">Provider</dt><dd class="font-semibold">{{ attempt.provider }}</dd></div><div class="flex justify-between gap-3"><dt class="text-neutral-500">Failure code</dt><dd class="font-mono text-xs">{{ attempt.failure_code || '—' }}</dd></div></dl><div v-if="attempt.failure_message" class="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{{ attempt.failure_message }}</div><pre v-if="attempt.metadata" class="mt-5 max-h-80 overflow-auto rounded-xl bg-neutral-950 p-4 text-xs text-neutral-200">{{ JSON.stringify(attempt.metadata, null, 2) }}</pre></section><section class="overflow-hidden rounded-2xl border border-neutral-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-neutral-200 px-5 py-4"><div><h2 class="font-semibold">Provider events</h2><p class="mt-1 text-xs text-neutral-500">Webhook timeline për këtë tentativë.</p></div><Webhook class="h-5 w-5 text-neutral-400" /></div><div v-if="attempt.events.length" class="divide-y divide-neutral-100"><Link v-for="event in attempt.events" :key="event.id" :href="`/super-admin/billing/provider-events/${event.id}`" class="flex items-center justify-between gap-3 px-5 py-4 text-sm no-underline hover:bg-neutral-50"><div><strong class="text-emerald-700">{{ event.event_type }}</strong><p class="mt-1 font-mono text-xs text-neutral-400">{{ event.external_id }}</p></div><div class="text-right"><span class="block text-xs font-semibold text-neutral-700">{{ event.status }}</span><span class="mt-1 block text-xs text-neutral-400">{{ dateTime(event.occurred_at) }}</span></div></Link></div><p v-else class="px-5 py-12 text-center text-sm text-neutral-400">Nuk ka evente të lidhura.</p></section></div>
        </div>
    </SuperAdminLayout>
</template>
