<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/** Weekly Albanian pricing narrative, generated by pricing:weekly-report. */
class PricingReport extends Model
{
    protected $fillable = ['week_start', 'title', 'body', 'highlights'];

    protected function casts(): array
    {
        return [
            'week_start' => 'date',
            'highlights' => 'array',
        ];
    }
}
